@ToDoListAPI_HostAddress = https://localhost:7029

GET {{ToDoListAPI_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ToDoListAPI_HostAddress}}/api/todoitems
Content-Type: application/json

{
  "name": "brush teeth",
  "isComplete": true
}

###
